// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.SuperSirAntsABot2.subsystems;

import org.usfirst.frc3244.SuperSirAntsABot2.Constants;
import org.usfirst.frc3244.SuperSirAntsABot2.RobotMap;
import org.usfirst.frc3244.SuperSirAntsABot2.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import com.ctre.phoenix.ParamEnum;
import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.FeedbackDevice;
import com.ctre.phoenix.motorcontrol.StatusFrameEnhanced;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Scissor extends Subsystem {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	public static final double CLIMB = 84;
	public static final double SCALE = 72;
	public static final double SWITCH = 24;
	public static final double DOWN = 0;
	
	private double m_encoderUnitsPerRev = 4096;
  	private double m_userUnitsPerRev = .625;
  	private double m_encoderUnitsPeruserUnits = m_encoderUnitsPerRev/m_userUnitsPerRev;//6553.6
  	
  	private double m_targetPositionRotations = 0;
	private static final double m_maxHeight = 11.5;
	private static final double m_minHeight = 0.25;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final WPI_TalonSRX motor_Right = RobotMap.scissorMotor_Right;
    private final WPI_TalonSRX motor_Left = RobotMap.scissorMotor_Left;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // member variables for Mecanum drive
  	private static final int kMaxNumberOfMotors = 2;
  	private final int m_invertedMotors[] = new int[kMaxNumberOfMotors];
  	private static final int kMotorLeft = 0;
  	private static final int kMotorRight = 1;
  	
  	// create objects needed for independent control of each wheel
  	private WPI_TalonSRX[] m_talons = new WPI_TalonSRX[kMaxNumberOfMotors];
  	private double m_zeroPositions[] = new double[kMaxNumberOfMotors];
  	
 // member variables to support closed loop mode
  	private boolean m_closedLoopMode = true;
  	private ControlMode m_closedLoopMode2018;
  	private double m_maxWheelSpeed = 445; //(10.5 Gear box = 445)//360(12.75 gear box);//550.0;     // empirically measured around 560 to 580	
  	private int m_CruiseVelocity = 300;
	private int m_Acceleration = 300;
	
    public Scissor() {
    	int talonIndex = 0;

    	// construct the talons
    	m_talons[kMotorLeft] = motor_Left;
    	m_talons[kMotorRight] = motor_Right;
    	
    	/* first choose the sensor */
    	for (talonIndex = 0; talonIndex < kMaxNumberOfMotors; talonIndex++) {
    		m_talons[talonIndex].configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Relative, Constants.kPIDLoopIdx, Constants.kTimeoutMs);
    		m_talons[talonIndex].setSensorPhase(false);
    		m_talons[talonIndex].setInverted(false);
    	}
		
		/* Set relevant frame periods to be at least as fast as periodic rate*/
    	for (talonIndex = 0; talonIndex < kMaxNumberOfMotors; talonIndex++) {
    		m_talons[talonIndex].setStatusFramePeriod(StatusFrameEnhanced.Status_13_Base_PIDF0, 10, Constants.kTimeoutMs);
    		m_talons[talonIndex].setStatusFramePeriod(StatusFrameEnhanced.Status_10_MotionMagic, 10, Constants.kTimeoutMs);
    	}

		/* set the peak and nominal outputs, 12V means full */
    	for (talonIndex = 0; talonIndex < kMaxNumberOfMotors; talonIndex++) {
    		m_talons[talonIndex].configNominalOutputForward(0, Constants.kTimeoutMs);
    		m_talons[talonIndex].configNominalOutputReverse(0, Constants.kTimeoutMs);
    		m_talons[talonIndex].configPeakOutputForward(1, Constants.kTimeoutMs);
    		m_talons[talonIndex].configPeakOutputReverse(-1, Constants.kTimeoutMs);
    	}
    	
		/* set acceleration and vcruise velocity - see documentation */
		for (talonIndex = 0; talonIndex < kMaxNumberOfMotors; talonIndex++) {
			m_talons[talonIndex].configMotionCruiseVelocity(m_CruiseVelocity, Constants.kTimeoutMs);
			m_talons[talonIndex].configMotionAcceleration(m_Acceleration, Constants.kTimeoutMs);
		}
		/* zero the sensor */
		for (talonIndex = 0; talonIndex < kMaxNumberOfMotors; talonIndex++) {
			m_talons[talonIndex].setSelectedSensorPosition(0, Constants.kPIDLoopIdx, Constants.kTimeoutMs);
		}
			
		//Configure Talon to clear sensor position on Reverse Limit
		for (talonIndex = 0; talonIndex < kMaxNumberOfMotors; talonIndex++) {
			m_talons[talonIndex].configSetParameter(ParamEnum.eClearPositionOnLimitF, 1, 0, 0, 10);
		}
    }
    
    
    public void init() {
		// complete initialization here that can't be performed in constructor
		// (some calls can't be made in constructor because other objects don't
		// yet exist)

		// Set up the TalonSRX closed loop / open loop mode for each wheel
		if (m_closedLoopMode) {
			setClosedLoopMode();
		} else {
			setOpenLoopMode();
		}
	}
    
    public void setClosedLoopMode() {
		m_closedLoopMode2018 = ControlMode.Position;
		
		int talonIndex = 0;
		m_closedLoopMode = true;
		setPIDF();
		/*for (talonIndex = 0; talonIndex < kMaxNumberOfMotors; talonIndex++) {
			m_talons[talonIndex].changeControlMode(TalonControlMode.Speed);
			m_talons[talonIndex].enableControl();
			
		}*/
		
	}
    public void setOpenLoopMode() {
		m_closedLoopMode2018 = ControlMode.PercentOutput;
		/*
		int talonIndex = 0;
		m_closedLoopMode = false;
		for (talonIndex = 0; talonIndex < kMaxNumberOfMotors; talonIndex++) {
			m_talons[talonIndex].changeControlMode(TalonControlMode.PercentVbus);
			m_talons[talonIndex].enableControl();
		}
		*/
	}

    public void setPIDF() {
    	int talonIndex = 0;
		double scissorkP = 0.09;///RobotPreferences.getScissorkP();
		double scissorkI = 0.0;//RobotPreferences.getScissorkI();
		double scissorkD = 0.0;//RobotPreferences.getScissorkD();
		double scissorkF = 0.314;//RobotPreferences.getScissorkF();
		
    	/* set closed loop gains in slot0 */
    	for (talonIndex = 0; talonIndex < kMaxNumberOfMotors; talonIndex++) {
    		m_talons[talonIndex].config_kF(Constants.kPIDLoopIdx, scissorkF, Constants.kTimeoutMs);
    		m_talons[talonIndex].config_kP(Constants.kPIDLoopIdx, scissorkP, Constants.kTimeoutMs);
    		m_talons[talonIndex].config_kI(Constants.kPIDLoopIdx, scissorkI, Constants.kTimeoutMs);
    		m_talons[talonIndex].config_kD(Constants.kPIDLoopIdx, scissorkD, Constants.kTimeoutMs);
    	}
    }
    
	
    
    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
    	m_talons[0].set(ControlMode.MotionMagic, m_targetPositionRotations);
    	m_talons[1].set(ControlMode.MotionMagic, m_targetPositionRotations);
    	SmartDashboard.putNumber("TargetPos", m_targetPositionRotations);
    	SmartDashboard.putNumber("AccPos", m_talons[1].getSelectedSensorPosition(0));
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void my_scissor_height(double height) {
    	height = clampInPut(height);
    	m_targetPositionRotations = height * m_encoderUnitsPeruserUnits;
    	//motor_Left_Slave.set(ControlMode.Follower, value);
    	//motor_Right_Master.set(ControlMode.Position, height);
    	
    }
    
    private double clampInPut(double input) {
    	if(input > m_maxHeight) {
    		return m_maxHeight;
    	}else if(input < m_minHeight) {
    		return m_minHeight;
    	}else {
    		return input;
    	}
    }

}

