// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.HungryVonHippo.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;

import org.usfirst.frc3244.HungryVonHippo.Robot;
import org.usfirst.frc3244.HungryVonHippo.subsystems.*;

/**
 *
 */
public class CG_Leave_Gear_On_Peg extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public CG_Leave_Gear_On_Peg() {
    	addSequential(new Wrist_to_Setpoint(Robot.wrist.DOWN-20),.5); //was 1.0
    	addSequential(new Drive_For_Distance_InTeleop(0.3, 0.0, 0, 5),3);
    	addSequential(new Wrist_to_Setpoint(Robot.wrist.UP),0.5);
    } 
}
